# Zahlenraten

import random as rand


def selber_raten():
    rand.seed()
    random_number = rand.randrange(1, 1024)
    print('Try to guess the number between 1 and 1024 generated by the script:')
    guess = False
    while guess is not True:
        guess_nr = int(input('--> '))
        if random_number > guess_nr:
            print('Number larger than guess')
        if random_number < guess_nr:
            print('Number smaller than guess')
        if random_number == guess_nr:
            print('Correct guess!')
            guess = True


def computer_raten():
    rand.seed()
    print('Think of a random number between 1 and 1024 that the script will try to guess.')
    print('If the guess is too large put \'g\', if the guess too small put \'k\' and if the guess is correct put \'r\'.')
    guess = False
    min_guess = 1
    max_guess = 1023
    while guess is not True:
        guess_nr = min_guess + ((max_guess - min_guess) // 2)
        print('Is', guess_nr, 'your number?')
        user_feedback = input('g/k/r? --> ')
        if user_feedback == 'g':
            max_guess = guess_nr
        if user_feedback == 'k':
            min_guess = guess_nr
        if user_feedback == 'r':
            print('Number was correctly guessed, exiting script..')
            guess = True


# selber_raten()
computer_raten()
